name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e # tag=v2
      - uses: actions/setup-node@5b949b50c3461bbcd5a540b150c368278160234a # tag=v3
        with:
          node-version: '16'
      - run: npm install
      - run: npm run build
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        env:
          # secrets.GITHUB_TOKEN does not have necessary permissions
          GH_TOKEN: ${{ secrets.SEMENTIC_AND_DEPBOT_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
