name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2
      - uses: actions/setup-node@56337c425554a6be30cdef71bf441f15be286854 # tag=v3
        with:
          node-version: '16'
      - run: npm install
      - run: npm run build
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        env:
          # secrets.GITHUB_TOKEN does not have necessary permissions
          GH_TOKEN: ${{ secrets.SEMENTIC_AND_DEPBOT_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
